/* Automatically @generated by tree-sitter v0.25.5 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 72
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_LT_SLASH = 3,
  anon_sym_SLASH_GT = 4,
  anon_sym_LT_BANGDOCTYPE = 5,
  aux_sym_doctype_token1 = 6,
  anon_sym_html = 7,
  sym_tag_name = 8,
  anon_sym_EQ = 9,
  sym_attribute_name = 10,
  sym_attribute_value = 11,
  anon_sym_DQUOTE = 12,
  aux_sym_quoted_attribute_value_token1 = 13,
  anon_sym_SQUOTE = 14,
  aux_sym_quoted_attribute_value_token2 = 15,
  anon_sym_AT = 16,
  anon_sym_BANG = 17,
  anon_sym_ATend = 18,
  anon_sym_ATelse = 19,
  anon_sym_ATelseif = 20,
  sym_directive_name = 21,
  anon_sym_LPAREN = 22,
  anon_sym_RPAREN = 23,
  anon_sym_COMMA = 24,
  anon_sym_in = 25,
  anon_sym_DOT = 26,
  anon_sym_LBRACE = 27,
  anon_sym_RBRACE = 28,
  anon_sym_LBRACK = 29,
  anon_sym_RBRACK = 30,
  anon_sym_COLON = 31,
  sym_param_identifier = 32,
  sym_param_number = 33,
  anon_sym_LBRACE_LBRACE = 34,
  aux_sym_output_expression_token1 = 35,
  anon_sym_RBRACE_RBRACE = 36,
  anon_sym_LBRACE_LBRACE_LBRACE = 37,
  anon_sym_RBRACE_RBRACE_RBRACE = 38,
  sym_comment = 39,
  sym_text_content = 40,
  sym_source_file = 41,
  sym__content = 42,
  sym_html_tag = 43,
  sym_start_tag = 44,
  sym_end_tag = 45,
  sym_self_closing_tag = 46,
  sym_doctype = 47,
  sym_attribute = 48,
  sym_quoted_attribute_value = 49,
  sym_directive = 50,
  sym_directive_statement = 51,
  sym_directive_keyword = 52,
  sym_directive_params = 53,
  sym_parameter_list = 54,
  sym_single_parameter = 55,
  sym_parameter_sequence = 56,
  sym_each_parameter = 57,
  sym_param_value = 58,
  sym_param_member_expression = 59,
  sym_param_object = 60,
  sym_object_content = 61,
  sym_param_array = 62,
  sym_array_content = 63,
  sym_param_property = 64,
  sym_param_string = 65,
  sym_output_expression = 66,
  aux_sym_source_file_repeat1 = 67,
  aux_sym_start_tag_repeat1 = 68,
  aux_sym_parameter_sequence_repeat1 = 69,
  aux_sym_param_member_expression_repeat1 = 70,
  aux_sym_object_content_repeat1 = 71,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_BANGDOCTYPE] = "<!DOCTYPE",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_html] = "html",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token1] = "quoted_attribute_value_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token2] = "quoted_attribute_value_token2",
  [anon_sym_AT] = "@",
  [anon_sym_BANG] = "!",
  [anon_sym_ATend] = "@end",
  [anon_sym_ATelse] = "@else",
  [anon_sym_ATelseif] = "@elseif",
  [sym_directive_name] = "directive_name",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_in] = "in",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [sym_param_identifier] = "param_identifier",
  [sym_param_number] = "param_number",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [aux_sym_output_expression_token1] = "output_expression_token1",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_LBRACE_LBRACE] = "{{{",
  [anon_sym_RBRACE_RBRACE_RBRACE] = "}}}",
  [sym_comment] = "comment",
  [sym_text_content] = "text_content",
  [sym_source_file] = "source_file",
  [sym__content] = "_content",
  [sym_html_tag] = "html_tag",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_doctype] = "doctype",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_directive] = "directive",
  [sym_directive_statement] = "directive_statement",
  [sym_directive_keyword] = "directive_keyword",
  [sym_directive_params] = "directive_params",
  [sym_parameter_list] = "parameter_list",
  [sym_single_parameter] = "single_parameter",
  [sym_parameter_sequence] = "parameter_sequence",
  [sym_each_parameter] = "each_parameter",
  [sym_param_value] = "param_value",
  [sym_param_member_expression] = "param_member_expression",
  [sym_param_object] = "param_object",
  [sym_object_content] = "object_content",
  [sym_param_array] = "param_array",
  [sym_array_content] = "array_content",
  [sym_param_property] = "param_property",
  [sym_param_string] = "param_string",
  [sym_output_expression] = "output_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_parameter_sequence_repeat1] = "parameter_sequence_repeat1",
  [aux_sym_param_member_expression_repeat1] = "param_member_expression_repeat1",
  [aux_sym_object_content_repeat1] = "object_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_BANGDOCTYPE] = anon_sym_LT_BANGDOCTYPE,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_html] = anon_sym_html,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token1] = aux_sym_quoted_attribute_value_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token2] = aux_sym_quoted_attribute_value_token2,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_ATend] = anon_sym_ATend,
  [anon_sym_ATelse] = anon_sym_ATelse,
  [anon_sym_ATelseif] = anon_sym_ATelseif,
  [sym_directive_name] = sym_directive_name,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_param_identifier] = sym_param_identifier,
  [sym_param_number] = sym_param_number,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [aux_sym_output_expression_token1] = aux_sym_output_expression_token1,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE_RBRACE,
  [sym_comment] = sym_comment,
  [sym_text_content] = sym_text_content,
  [sym_source_file] = sym_source_file,
  [sym__content] = sym__content,
  [sym_html_tag] = sym_html_tag,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_doctype] = sym_doctype,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_directive] = sym_directive,
  [sym_directive_statement] = sym_directive_statement,
  [sym_directive_keyword] = sym_directive_keyword,
  [sym_directive_params] = sym_directive_params,
  [sym_parameter_list] = sym_parameter_list,
  [sym_single_parameter] = sym_single_parameter,
  [sym_parameter_sequence] = sym_parameter_sequence,
  [sym_each_parameter] = sym_each_parameter,
  [sym_param_value] = sym_param_value,
  [sym_param_member_expression] = sym_param_member_expression,
  [sym_param_object] = sym_param_object,
  [sym_object_content] = sym_object_content,
  [sym_param_array] = sym_param_array,
  [sym_array_content] = sym_array_content,
  [sym_param_property] = sym_param_property,
  [sym_param_string] = sym_param_string,
  [sym_output_expression] = sym_output_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_parameter_sequence_repeat1] = aux_sym_parameter_sequence_repeat1,
  [aux_sym_param_member_expression_repeat1] = aux_sym_param_member_expression_repeat1,
  [aux_sym_object_content_repeat1] = aux_sym_object_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_BANGDOCTYPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_html] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATelse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATelseif] = {
    .visible = true,
    .named = false,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_param_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_param_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_output_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__content] = {
    .visible = false,
    .named = true,
  },
  [sym_html_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_params] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_single_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_each_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_param_value] = {
    .visible = true,
    .named = true,
  },
  [sym_param_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_param_object] = {
    .visible = true,
    .named = true,
  },
  [sym_object_content] = {
    .visible = true,
    .named = true,
  },
  [sym_param_array] = {
    .visible = true,
    .named = true,
  },
  [sym_array_content] = {
    .visible = true,
    .named = true,
  },
  [sym_param_property] = {
    .visible = true,
    .named = true,
  },
  [sym_param_string] = {
    .visible = true,
    .named = true,
  },
  [sym_output_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_member_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '!', 55,
        '"', 48,
        '\'', 51,
        '(', 60,
        ')', 61,
        ',', 62,
        '.', 64,
        '/', 8,
        ':', 70,
        '<', 37,
        '=', 45,
        '>', 38,
        '@', 54,
        '[', 68,
        ']', 69,
        'h', 24,
        'i', 22,
        '{', 66,
        '}', 67,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(55);
      if (lookahead == '}') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(48);
      if (lookahead == '\'') ADVANCE(51);
      if (lookahead == ')') ADVANCE(61);
      if (lookahead == '[') ADVANCE(68);
      if (lookahead == ']') ADVANCE(69);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '}') ADVANCE(67);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(48);
      if (lookahead == '\'') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '`') ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(26);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '=') ADVANCE(45);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == '}') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead == 'C') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'D') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 'O') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == 'P') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == 'Y') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(56);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(58);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(23);
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(63);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 25:
      if (lookahead == '{') ADVANCE(74);
      END_STATE();
    case 26:
      if (lookahead == '}') ADVANCE(27);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 27:
      if (lookahead == '}') ADVANCE(80);
      END_STATE();
    case 28:
      if (lookahead == '}') ADVANCE(77);
      END_STATE();
    case 29:
      if (lookahead == '}') ADVANCE(79);
      END_STATE();
    case 30:
      if (lookahead == '}') ADVANCE(29);
      END_STATE();
    case 31:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 32:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 34:
      if (eof) ADVANCE(36);
      if (lookahead == '(') ADVANCE(60);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '@') ADVANCE(54);
      if (lookahead == '{') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 35:
      if (eof) ADVANCE(36);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '@') ADVANCE(54);
      if (lookahead == '{') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(10);
      if (lookahead == '/') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT_BANGDOCTYPE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_html);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '`') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_ATelse);
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_ATelseif);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_param_identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_param_number);
      if (lookahead == '.') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_param_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '{') ADVANCE(78);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_output_expression_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_output_expression_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_LBRACE);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE_RBRACE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '(') ADVANCE(60);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '@') ADVANCE(54);
      if (lookahead == '{') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '@') ADVANCE(54);
      if (lookahead == '{') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '@' &&
          lookahead != '{') ADVANCE(83);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 35},
  [2] = {.lex_state = 35},
  [3] = {.lex_state = 35},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 34},
  [6] = {.lex_state = 34},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 35},
  [9] = {.lex_state = 35},
  [10] = {.lex_state = 35},
  [11] = {.lex_state = 35},
  [12] = {.lex_state = 35},
  [13] = {.lex_state = 35},
  [14] = {.lex_state = 35},
  [15] = {.lex_state = 35},
  [16] = {.lex_state = 35},
  [17] = {.lex_state = 35},
  [18] = {.lex_state = 35},
  [19] = {.lex_state = 35},
  [20] = {.lex_state = 35},
  [21] = {.lex_state = 35},
  [22] = {.lex_state = 35},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 52},
  [57] = {.lex_state = 49},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 75},
  [60] = {.lex_state = 75},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 31},
  [65] = {.lex_state = 32},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 49},
  [72] = {.lex_state = 52},
  [73] = {.lex_state = 31},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_BANGDOCTYPE] = ACTIONS(1),
    [anon_sym_html] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [anon_sym_ATelse] = ACTIONS(1),
    [anon_sym_ATelseif] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_param_number] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(85),
    [sym__content] = STATE(2),
    [sym_html_tag] = STATE(2),
    [sym_start_tag] = STATE(19),
    [sym_end_tag] = STATE(19),
    [sym_self_closing_tag] = STATE(19),
    [sym_doctype] = STATE(2),
    [sym_directive] = STATE(2),
    [sym_directive_statement] = STATE(11),
    [sym_directive_keyword] = STATE(11),
    [sym_output_expression] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [anon_sym_LT_SLASH] = ACTIONS(7),
    [anon_sym_LT_BANGDOCTYPE] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_ATend] = ACTIONS(13),
    [anon_sym_ATelse] = ACTIONS(13),
    [anon_sym_ATelseif] = ACTIONS(13),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(17),
    [sym_comment] = ACTIONS(19),
    [sym_text_content] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LT_SLASH,
    ACTIONS(9), 1,
      anon_sym_LT_BANGDOCTYPE,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 2,
      sym_comment,
      sym_text_content,
    STATE(11), 2,
      sym_directive_statement,
      sym_directive_keyword,
    ACTIONS(13), 3,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
    STATE(19), 3,
      sym_start_tag,
      sym_end_tag,
      sym_self_closing_tag,
    STATE(3), 6,
      sym__content,
      sym_html_tag,
      sym_doctype,
      sym_directive,
      sym_output_expression,
      aux_sym_source_file_repeat1,
  [48] = 12,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_LT,
    ACTIONS(30), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      anon_sym_LT_BANGDOCTYPE,
    ACTIONS(36), 1,
      anon_sym_AT,
    ACTIONS(42), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(48), 2,
      sym_comment,
      sym_text_content,
    STATE(11), 2,
      sym_directive_statement,
      sym_directive_keyword,
    ACTIONS(39), 3,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
    STATE(19), 3,
      sym_start_tag,
      sym_end_tag,
      sym_self_closing_tag,
    STATE(3), 6,
      sym__content,
      sym_html_tag,
      sym_doctype,
      sym_directive,
      sym_output_expression,
      aux_sym_source_file_repeat1,
  [96] = 11,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_SQUOTE,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      sym_param_identifier,
    ACTIONS(63), 1,
      sym_param_number,
    STATE(46), 1,
      sym_param_value,
    STATE(63), 1,
      sym_parameter_list,
    STATE(81), 3,
      sym_single_parameter,
      sym_parameter_sequence,
      sym_each_parameter,
    STATE(40), 4,
      sym_param_member_expression,
      sym_param_object,
      sym_param_array,
      sym_param_string,
  [135] = 4,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_directive_params,
    ACTIONS(67), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [158] = 4,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      sym_directive_params,
    ACTIONS(73), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [181] = 10,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_SQUOTE,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      sym_param_number,
    ACTIONS(75), 1,
      anon_sym_RBRACK,
    ACTIONS(77), 1,
      sym_param_identifier,
    STATE(49), 1,
      sym_param_value,
    STATE(82), 1,
      sym_array_content,
    STATE(40), 4,
      sym_param_member_expression,
      sym_param_object,
      sym_param_array,
      sym_param_string,
  [215] = 2,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [232] = 2,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [249] = 2,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [266] = 2,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [283] = 2,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [300] = 2,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [317] = 2,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [334] = 2,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [351] = 2,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [368] = 2,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [385] = 2,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [402] = 2,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [419] = 2,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [436] = 2,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [453] = 2,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [470] = 8,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_SQUOTE,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      sym_param_number,
    ACTIONS(77), 1,
      sym_param_identifier,
    STATE(61), 1,
      sym_param_value,
    STATE(40), 4,
      sym_param_member_expression,
      sym_param_object,
      sym_param_array,
      sym_param_string,
  [498] = 8,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_SQUOTE,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      sym_param_number,
    ACTIONS(77), 1,
      sym_param_identifier,
    STATE(77), 1,
      sym_param_value,
    STATE(40), 4,
      sym_param_member_expression,
      sym_param_object,
      sym_param_array,
      sym_param_string,
  [526] = 8,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_SQUOTE,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      sym_param_number,
    ACTIONS(77), 1,
      sym_param_identifier,
    STATE(53), 1,
      sym_param_value,
    STATE(40), 4,
      sym_param_member_expression,
      sym_param_object,
      sym_param_array,
      sym_param_string,
  [554] = 7,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_SQUOTE,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(137), 1,
      sym_param_identifier,
    STATE(51), 1,
      sym_param_property,
    STATE(66), 1,
      sym_object_content,
    STATE(80), 1,
      sym_param_string,
  [576] = 3,
    ACTIONS(141), 1,
      anon_sym_DOT,
    STATE(28), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(139), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [589] = 3,
    ACTIONS(141), 1,
      anon_sym_DOT,
    STATE(29), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(143), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [602] = 3,
    ACTIONS(147), 1,
      anon_sym_DOT,
    STATE(29), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(145), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [615] = 4,
    ACTIONS(141), 1,
      anon_sym_DOT,
    ACTIONS(150), 1,
      anon_sym_in,
    STATE(28), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(139), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [629] = 4,
    ACTIONS(152), 1,
      anon_sym_GT,
    ACTIONS(154), 1,
      anon_sym_SLASH_GT,
    ACTIONS(156), 1,
      sym_attribute_name,
    STATE(32), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [643] = 3,
    ACTIONS(160), 1,
      sym_attribute_name,
    ACTIONS(158), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(32), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [655] = 1,
    ACTIONS(163), 5,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_COLON,
  [663] = 4,
    ACTIONS(156), 1,
      sym_attribute_name,
    ACTIONS(165), 1,
      anon_sym_GT,
    ACTIONS(167), 1,
      anon_sym_SLASH_GT,
    STATE(31), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [677] = 1,
    ACTIONS(145), 5,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [685] = 5,
    ACTIONS(51), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_SQUOTE,
    ACTIONS(137), 1,
      sym_param_identifier,
    STATE(62), 1,
      sym_param_property,
    STATE(80), 1,
      sym_param_string,
  [701] = 2,
    ACTIONS(171), 1,
      anon_sym_EQ,
    ACTIONS(169), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [710] = 1,
    ACTIONS(173), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [717] = 1,
    ACTIONS(175), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [724] = 1,
    ACTIONS(139), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [731] = 4,
    ACTIONS(177), 1,
      sym_attribute_value,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
    STATE(47), 1,
      sym_quoted_attribute_value,
  [744] = 1,
    ACTIONS(183), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [751] = 1,
    ACTIONS(185), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [758] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_parameter_sequence_repeat1,
    ACTIONS(187), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [769] = 3,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_object_content_repeat1,
  [779] = 3,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_parameter_sequence_repeat1,
  [789] = 1,
    ACTIONS(200), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [795] = 1,
    ACTIONS(202), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [801] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_parameter_sequence_repeat1,
  [811] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym_parameter_sequence_repeat1,
  [821] = 3,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      aux_sym_object_content_repeat1,
  [831] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_parameter_sequence_repeat1,
  [841] = 1,
    ACTIONS(187), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [847] = 1,
    ACTIONS(212), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [853] = 3,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_object_content_repeat1,
  [863] = 2,
    ACTIONS(219), 1,
      anon_sym_SQUOTE,
    ACTIONS(221), 1,
      aux_sym_quoted_attribute_value_token2,
  [870] = 2,
    ACTIONS(219), 1,
      anon_sym_DQUOTE,
    ACTIONS(223), 1,
      aux_sym_quoted_attribute_value_token1,
  [877] = 2,
    ACTIONS(225), 1,
      anon_sym_BANG,
    ACTIONS(227), 1,
      sym_directive_name,
  [884] = 2,
    ACTIONS(229), 1,
      aux_sym_output_expression_token1,
    ACTIONS(231), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [891] = 2,
    ACTIONS(231), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(233), 1,
      aux_sym_output_expression_token1,
  [898] = 1,
    ACTIONS(235), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [903] = 1,
    ACTIONS(217), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [908] = 1,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
  [912] = 1,
    ACTIONS(239), 1,
      sym_tag_name,
  [916] = 1,
    ACTIONS(241), 1,
      aux_sym_doctype_token1,
  [920] = 1,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
  [924] = 1,
    ACTIONS(245), 1,
      anon_sym_SQUOTE,
  [928] = 1,
    ACTIONS(247), 1,
      anon_sym_DQUOTE,
  [932] = 1,
    ACTIONS(247), 1,
      anon_sym_SQUOTE,
  [936] = 1,
    ACTIONS(249), 1,
      anon_sym_RBRACE_RBRACE,
  [940] = 1,
    ACTIONS(251), 1,
      aux_sym_quoted_attribute_value_token1,
  [944] = 1,
    ACTIONS(253), 1,
      aux_sym_quoted_attribute_value_token2,
  [948] = 1,
    ACTIONS(255), 1,
      sym_tag_name,
  [952] = 1,
    ACTIONS(257), 1,
      anon_sym_GT,
  [956] = 1,
    ACTIONS(245), 1,
      anon_sym_DQUOTE,
  [960] = 1,
    ACTIONS(259), 1,
      anon_sym_GT,
  [964] = 1,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
  [968] = 1,
    ACTIONS(263), 1,
      anon_sym_html,
  [972] = 1,
    ACTIONS(265), 1,
      sym_directive_name,
  [976] = 1,
    ACTIONS(267), 1,
      anon_sym_COLON,
  [980] = 1,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
  [984] = 1,
    ACTIONS(271), 1,
      anon_sym_RBRACK,
  [988] = 1,
    ACTIONS(249), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [992] = 1,
    ACTIONS(273), 1,
      sym_param_identifier,
  [996] = 1,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 158,
  [SMALL_STATE(7)] = 181,
  [SMALL_STATE(8)] = 215,
  [SMALL_STATE(9)] = 232,
  [SMALL_STATE(10)] = 249,
  [SMALL_STATE(11)] = 266,
  [SMALL_STATE(12)] = 283,
  [SMALL_STATE(13)] = 300,
  [SMALL_STATE(14)] = 317,
  [SMALL_STATE(15)] = 334,
  [SMALL_STATE(16)] = 351,
  [SMALL_STATE(17)] = 368,
  [SMALL_STATE(18)] = 385,
  [SMALL_STATE(19)] = 402,
  [SMALL_STATE(20)] = 419,
  [SMALL_STATE(21)] = 436,
  [SMALL_STATE(22)] = 453,
  [SMALL_STATE(23)] = 470,
  [SMALL_STATE(24)] = 498,
  [SMALL_STATE(25)] = 526,
  [SMALL_STATE(26)] = 554,
  [SMALL_STATE(27)] = 576,
  [SMALL_STATE(28)] = 589,
  [SMALL_STATE(29)] = 602,
  [SMALL_STATE(30)] = 615,
  [SMALL_STATE(31)] = 629,
  [SMALL_STATE(32)] = 643,
  [SMALL_STATE(33)] = 655,
  [SMALL_STATE(34)] = 663,
  [SMALL_STATE(35)] = 677,
  [SMALL_STATE(36)] = 685,
  [SMALL_STATE(37)] = 701,
  [SMALL_STATE(38)] = 710,
  [SMALL_STATE(39)] = 717,
  [SMALL_STATE(40)] = 724,
  [SMALL_STATE(41)] = 731,
  [SMALL_STATE(42)] = 744,
  [SMALL_STATE(43)] = 751,
  [SMALL_STATE(44)] = 758,
  [SMALL_STATE(45)] = 769,
  [SMALL_STATE(46)] = 779,
  [SMALL_STATE(47)] = 789,
  [SMALL_STATE(48)] = 795,
  [SMALL_STATE(49)] = 801,
  [SMALL_STATE(50)] = 811,
  [SMALL_STATE(51)] = 821,
  [SMALL_STATE(52)] = 831,
  [SMALL_STATE(53)] = 841,
  [SMALL_STATE(54)] = 847,
  [SMALL_STATE(55)] = 853,
  [SMALL_STATE(56)] = 863,
  [SMALL_STATE(57)] = 870,
  [SMALL_STATE(58)] = 877,
  [SMALL_STATE(59)] = 884,
  [SMALL_STATE(60)] = 891,
  [SMALL_STATE(61)] = 898,
  [SMALL_STATE(62)] = 903,
  [SMALL_STATE(63)] = 908,
  [SMALL_STATE(64)] = 912,
  [SMALL_STATE(65)] = 916,
  [SMALL_STATE(66)] = 920,
  [SMALL_STATE(67)] = 924,
  [SMALL_STATE(68)] = 928,
  [SMALL_STATE(69)] = 932,
  [SMALL_STATE(70)] = 936,
  [SMALL_STATE(71)] = 940,
  [SMALL_STATE(72)] = 944,
  [SMALL_STATE(73)] = 948,
  [SMALL_STATE(74)] = 952,
  [SMALL_STATE(75)] = 956,
  [SMALL_STATE(76)] = 960,
  [SMALL_STATE(77)] = 964,
  [SMALL_STATE(78)] = 968,
  [SMALL_STATE(79)] = 972,
  [SMALL_STATE(80)] = 976,
  [SMALL_STATE(81)] = 980,
  [SMALL_STATE(82)] = 984,
  [SMALL_STATE(83)] = 988,
  [SMALL_STATE(84)] = 992,
  [SMALL_STATE(85)] = 996,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_statement, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_statement, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_statement, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_statement, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_expression, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_expression, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_expression, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_expression, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_statement, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_statement, 4, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_params, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_params, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_tag, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_tag, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_params, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_params, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_keyword, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_keyword, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_value, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_member_expression, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_member_expression_repeat1, 2, 0, 0),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_member_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_string, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_array, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_object, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_array, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_object, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_sequence_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_content, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_parameter, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_content, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_content, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_content, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_sequence, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_content_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_content_repeat1, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_property, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_parameter, 3, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [275] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_edge(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "edge",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
