/* Automatically @generated by tree-sitter v0.25.5 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 126
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 77
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_LT_SLASH = 3,
  anon_sym_SLASH_GT = 4,
  anon_sym_LT_BANGDOCTYPE = 5,
  aux_sym_doctype_token1 = 6,
  anon_sym_html = 7,
  sym_tag_name = 8,
  anon_sym_EQ = 9,
  sym_attribute_name = 10,
  sym_attribute_value = 11,
  anon_sym_DQUOTE = 12,
  anon_sym_SQUOTE = 13,
  sym_attribute_text = 14,
  anon_sym_AT = 15,
  anon_sym_BANG = 16,
  anon_sym_DOT = 17,
  anon_sym_ATend = 18,
  anon_sym_ATelse = 19,
  anon_sym_ATelseif = 20,
  aux_sym_directive_name_token1 = 21,
  anon_sym_LPAREN = 22,
  anon_sym_RPAREN = 23,
  anon_sym_COMMA = 24,
  anon_sym_in = 25,
  anon_sym_LBRACE = 26,
  anon_sym_RBRACE = 27,
  anon_sym_COLON = 28,
  aux_sym_param_string_token1 = 29,
  aux_sym_param_string_token2 = 30,
  sym_param_number = 31,
  anon_sym_LBRACE_LBRACE = 32,
  anon_sym_RBRACE_RBRACE = 33,
  anon_sym_LBRACE_LBRACE_LBRACE = 34,
  anon_sym_RBRACE_RBRACE_RBRACE = 35,
  aux_sym_function_call_token1 = 36,
  sym_comment = 37,
  sym_text_content = 38,
  sym_source_file = 39,
  sym__content = 40,
  sym_html_tag = 41,
  sym_start_tag = 42,
  sym_end_tag = 43,
  sym_self_closing_tag = 44,
  sym_doctype = 45,
  sym_attribute = 46,
  sym_mixed_attribute_value = 47,
  sym_directive = 48,
  sym_directive_statement = 49,
  sym_directive_component = 50,
  sym_directive_keyword = 51,
  sym_directive_name = 52,
  sym_directive_method = 53,
  sym_directive_params = 54,
  sym_parameter_list = 55,
  sym_single_parameter = 56,
  sym_parameter_sequence = 57,
  sym_each_parameter = 58,
  sym_param_value = 59,
  sym_param_member_expression = 60,
  sym_param_object = 61,
  sym_param_property = 62,
  sym_param_identifier = 63,
  sym_param_string = 64,
  sym_output_expression = 65,
  sym_expression_content = 66,
  sym_function_call = 67,
  sym_member_expression = 68,
  sym_identifier = 69,
  aux_sym_source_file_repeat1 = 70,
  aux_sym_start_tag_repeat1 = 71,
  aux_sym_mixed_attribute_value_repeat1 = 72,
  aux_sym_parameter_sequence_repeat1 = 73,
  aux_sym_param_member_expression_repeat1 = 74,
  aux_sym_param_object_repeat1 = 75,
  aux_sym_member_expression_repeat1 = 76,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_BANGDOCTYPE] = "<!DOCTYPE",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_html] = "html",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [sym_attribute_text] = "attribute_text",
  [anon_sym_AT] = "@",
  [anon_sym_BANG] = "!",
  [anon_sym_DOT] = ".",
  [anon_sym_ATend] = "@end",
  [anon_sym_ATelse] = "@else",
  [anon_sym_ATelseif] = "@elseif",
  [aux_sym_directive_name_token1] = "directive_name_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_in] = "in",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [aux_sym_param_string_token1] = "param_string_token1",
  [aux_sym_param_string_token2] = "param_string_token2",
  [sym_param_number] = "param_number",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_LBRACE_LBRACE] = "{{{",
  [anon_sym_RBRACE_RBRACE_RBRACE] = "}}}",
  [aux_sym_function_call_token1] = "function_call_token1",
  [sym_comment] = "comment",
  [sym_text_content] = "text_content",
  [sym_source_file] = "source_file",
  [sym__content] = "_content",
  [sym_html_tag] = "html_tag",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_doctype] = "doctype",
  [sym_attribute] = "attribute",
  [sym_mixed_attribute_value] = "mixed_attribute_value",
  [sym_directive] = "directive",
  [sym_directive_statement] = "directive_statement",
  [sym_directive_component] = "directive_component",
  [sym_directive_keyword] = "directive_keyword",
  [sym_directive_name] = "directive_name",
  [sym_directive_method] = "directive_method",
  [sym_directive_params] = "directive_params",
  [sym_parameter_list] = "parameter_list",
  [sym_single_parameter] = "single_parameter",
  [sym_parameter_sequence] = "parameter_sequence",
  [sym_each_parameter] = "each_parameter",
  [sym_param_value] = "param_value",
  [sym_param_member_expression] = "param_member_expression",
  [sym_param_object] = "param_object",
  [sym_param_property] = "param_property",
  [sym_param_identifier] = "param_identifier",
  [sym_param_string] = "param_string",
  [sym_output_expression] = "output_expression",
  [sym_expression_content] = "expression_content",
  [sym_function_call] = "function_call",
  [sym_member_expression] = "member_expression",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_mixed_attribute_value_repeat1] = "mixed_attribute_value_repeat1",
  [aux_sym_parameter_sequence_repeat1] = "parameter_sequence_repeat1",
  [aux_sym_param_member_expression_repeat1] = "param_member_expression_repeat1",
  [aux_sym_param_object_repeat1] = "param_object_repeat1",
  [aux_sym_member_expression_repeat1] = "member_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_BANGDOCTYPE] = anon_sym_LT_BANGDOCTYPE,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_html] = anon_sym_html,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_attribute_text] = sym_attribute_text,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_ATend] = anon_sym_ATend,
  [anon_sym_ATelse] = anon_sym_ATelse,
  [anon_sym_ATelseif] = anon_sym_ATelseif,
  [aux_sym_directive_name_token1] = aux_sym_directive_name_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_param_string_token1] = aux_sym_param_string_token1,
  [aux_sym_param_string_token2] = aux_sym_param_string_token2,
  [sym_param_number] = sym_param_number,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE_RBRACE,
  [aux_sym_function_call_token1] = aux_sym_function_call_token1,
  [sym_comment] = sym_comment,
  [sym_text_content] = sym_text_content,
  [sym_source_file] = sym_source_file,
  [sym__content] = sym__content,
  [sym_html_tag] = sym_html_tag,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_doctype] = sym_doctype,
  [sym_attribute] = sym_attribute,
  [sym_mixed_attribute_value] = sym_mixed_attribute_value,
  [sym_directive] = sym_directive,
  [sym_directive_statement] = sym_directive_statement,
  [sym_directive_component] = sym_directive_component,
  [sym_directive_keyword] = sym_directive_keyword,
  [sym_directive_name] = sym_directive_name,
  [sym_directive_method] = sym_directive_method,
  [sym_directive_params] = sym_directive_params,
  [sym_parameter_list] = sym_parameter_list,
  [sym_single_parameter] = sym_single_parameter,
  [sym_parameter_sequence] = sym_parameter_sequence,
  [sym_each_parameter] = sym_each_parameter,
  [sym_param_value] = sym_param_value,
  [sym_param_member_expression] = sym_param_member_expression,
  [sym_param_object] = sym_param_object,
  [sym_param_property] = sym_param_property,
  [sym_param_identifier] = sym_param_identifier,
  [sym_param_string] = sym_param_string,
  [sym_output_expression] = sym_output_expression,
  [sym_expression_content] = sym_expression_content,
  [sym_function_call] = sym_function_call,
  [sym_member_expression] = sym_member_expression,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_mixed_attribute_value_repeat1] = aux_sym_mixed_attribute_value_repeat1,
  [aux_sym_parameter_sequence_repeat1] = aux_sym_parameter_sequence_repeat1,
  [aux_sym_param_member_expression_repeat1] = aux_sym_param_member_expression_repeat1,
  [aux_sym_param_object_repeat1] = aux_sym_param_object_repeat1,
  [aux_sym_member_expression_repeat1] = aux_sym_member_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_BANGDOCTYPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_html] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATelse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATelseif] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_param_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_param_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_function_call_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__content] = {
    .visible = false,
    .named = true,
  },
  [sym_html_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_mixed_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_component] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_method] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_params] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_single_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_each_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_param_value] = {
    .visible = true,
    .named = true,
  },
  [sym_param_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_param_object] = {
    .visible = true,
    .named = true,
  },
  [sym_param_property] = {
    .visible = true,
    .named = true,
  },
  [sym_param_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_param_string] = {
    .visible = true,
    .named = true,
  },
  [sym_output_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_content] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mixed_attribute_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_member_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_member_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 32,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 40,
  [42] = 31,
  [43] = 32,
  [44] = 31,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 14,
  [59] = 19,
  [60] = 52,
  [61] = 14,
  [62] = 19,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 66,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 72,
  [81] = 81,
  [82] = 79,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 88,
  [93] = 90,
  [94] = 84,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 99,
  [104] = 95,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 110,
  [118] = 98,
  [119] = 114,
  [120] = 120,
  [121] = 121,
  [122] = 121,
  [123] = 112,
  [124] = 98,
  [125] = 114,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '!', 59,
        '"', 53,
        '\'', 54,
        '(', 65,
        ')', 66,
        ',', 67,
        '.', 60,
        '/', 11,
        ':', 72,
        '<', 42,
        '=', 50,
        '>', 43,
        '@', 58,
        'h', 27,
        'i', 25,
        '{', 70,
        '}', 71,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(59);
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == ')') ADVANCE(66);
      if (lookahead == '{') ADVANCE(69);
      if (lookahead == '}') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\'') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '`') ADVANCE(52);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '{') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == '{') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(65);
      if (lookahead == '.') ADVANCE(60);
      if (lookahead == '}') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(65);
      if (lookahead == '.') ADVANCE(60);
      if (lookahead == '}') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(30);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == '=') ADVANCE(50);
      if (lookahead == '>') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(45);
      END_STATE();
    case 12:
      if (lookahead == 'C') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'D') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(46);
      END_STATE();
    case 15:
      if (lookahead == 'O') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 'P') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'T') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'Y') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(61);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(63);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == '{') ADVANCE(79);
      END_STATE();
    case 29:
      if (lookahead == '{') ADVANCE(80);
      END_STATE();
    case 30:
      if (lookahead == '}') ADVANCE(31);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 31:
      if (lookahead == '}') ADVANCE(86);
      END_STATE();
    case 32:
      if (lookahead == '}') ADVANCE(81);
      END_STATE();
    case 33:
      if (lookahead == '}') ADVANCE(83);
      END_STATE();
    case 34:
      if (lookahead == '}') ADVANCE(33);
      END_STATE();
    case 35:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 36:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 38:
      if (eof) ADVANCE(41);
      if (lookahead == '(') ADVANCE(65);
      if (lookahead == '.') ADVANCE(60);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '@') ADVANCE(58);
      if (lookahead == '{') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 39:
      if (eof) ADVANCE(41);
      if (lookahead == '(') ADVANCE(65);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '@') ADVANCE(58);
      if (lookahead == '{') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '@') ADVANCE(58);
      if (lookahead == '{') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(13);
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LT_BANGDOCTYPE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_html);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '`') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_attribute_text);
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '{') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_attribute_text);
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == '{') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_attribute_text);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_ATelse);
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_ATelseif);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_directive_name_token1);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(79);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_param_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_param_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_param_string_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_param_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_param_number);
      if (lookahead == '.') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_param_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '{') ADVANCE(82);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '{') ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_LBRACE);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE_RBRACE);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(85);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '(') ADVANCE(65);
      if (lookahead == '.') ADVANCE(60);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '@') ADVANCE(58);
      if (lookahead == '{') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '(') ADVANCE(65);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '@') ADVANCE(58);
      if (lookahead == '{') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '@') ADVANCE(58);
      if (lookahead == '{') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '@' &&
          lookahead != '{') ADVANCE(90);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 40},
  [2] = {.lex_state = 40},
  [3] = {.lex_state = 40},
  [4] = {.lex_state = 38},
  [5] = {.lex_state = 38},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 39},
  [8] = {.lex_state = 38},
  [9] = {.lex_state = 39},
  [10] = {.lex_state = 39},
  [11] = {.lex_state = 39},
  [12] = {.lex_state = 40},
  [13] = {.lex_state = 40},
  [14] = {.lex_state = 40},
  [15] = {.lex_state = 40},
  [16] = {.lex_state = 40},
  [17] = {.lex_state = 40},
  [18] = {.lex_state = 40},
  [19] = {.lex_state = 40},
  [20] = {.lex_state = 40},
  [21] = {.lex_state = 40},
  [22] = {.lex_state = 40},
  [23] = {.lex_state = 40},
  [24] = {.lex_state = 40},
  [25] = {.lex_state = 40},
  [26] = {.lex_state = 40},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 10},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 10},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 10},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 10},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 10},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 84},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 6},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 5},
  [94] = {.lex_state = 84},
  [95] = {.lex_state = 5},
  [96] = {.lex_state = 35},
  [97] = {.lex_state = 35},
  [98] = {.lex_state = 5},
  [99] = {.lex_state = 5},
  [100] = {.lex_state = 75},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 6},
  [104] = {.lex_state = 6},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 73},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 6},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 6},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 6},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 5},
  [118] = {.lex_state = 5},
  [119] = {.lex_state = 6},
  [120] = {.lex_state = 36},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 5},
  [124] = {.lex_state = 5},
  [125] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_BANGDOCTYPE] = ACTIONS(1),
    [anon_sym_html] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [anon_sym_ATelse] = ACTIONS(1),
    [anon_sym_ATelseif] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_param_number] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(113),
    [sym__content] = STATE(3),
    [sym_html_tag] = STATE(3),
    [sym_start_tag] = STATE(13),
    [sym_end_tag] = STATE(13),
    [sym_self_closing_tag] = STATE(13),
    [sym_doctype] = STATE(3),
    [sym_directive] = STATE(3),
    [sym_directive_statement] = STATE(12),
    [sym_directive_keyword] = STATE(12),
    [sym_output_expression] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [anon_sym_LT_SLASH] = ACTIONS(7),
    [anon_sym_LT_BANGDOCTYPE] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_ATend] = ACTIONS(13),
    [anon_sym_ATelse] = ACTIONS(13),
    [anon_sym_ATelseif] = ACTIONS(13),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(17),
    [sym_comment] = ACTIONS(19),
    [sym_text_content] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(26), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      anon_sym_LT_BANGDOCTYPE,
    ACTIONS(32), 1,
      anon_sym_AT,
    ACTIONS(38), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(41), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(44), 2,
      sym_comment,
      sym_text_content,
    STATE(12), 2,
      sym_directive_statement,
      sym_directive_keyword,
    ACTIONS(35), 3,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
    STATE(13), 3,
      sym_start_tag,
      sym_end_tag,
      sym_self_closing_tag,
    STATE(2), 6,
      sym__content,
      sym_html_tag,
      sym_doctype,
      sym_directive,
      sym_output_expression,
      aux_sym_source_file_repeat1,
  [48] = 12,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LT_SLASH,
    ACTIONS(9), 1,
      anon_sym_LT_BANGDOCTYPE,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 2,
      sym_comment,
      sym_text_content,
    STATE(12), 2,
      sym_directive_statement,
      sym_directive_keyword,
    ACTIONS(13), 3,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
    STATE(13), 3,
      sym_start_tag,
      sym_end_tag,
      sym_self_closing_tag,
    STATE(2), 6,
      sym__content,
      sym_html_tag,
      sym_doctype,
      sym_directive,
      sym_output_expression,
      aux_sym_source_file_repeat1,
  [96] = 5,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_directive_params,
    ACTIONS(53), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [122] = 5,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_directive_params,
    ACTIONS(61), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [148] = 11,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      sym_param_number,
    STATE(47), 1,
      sym_param_identifier,
    STATE(81), 1,
      sym_param_value,
    STATE(102), 1,
      sym_parameter_list,
    STATE(75), 3,
      sym_param_member_expression,
      sym_param_object,
      sym_param_string,
    STATE(105), 3,
      sym_single_parameter,
      sym_parameter_sequence,
      sym_each_parameter,
  [186] = 4,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_directive_params,
    ACTIONS(53), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [209] = 2,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 13,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LPAREN,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [228] = 4,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_directive_params,
    ACTIONS(61), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [251] = 2,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 12,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LPAREN,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [269] = 2,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 12,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LPAREN,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [287] = 2,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [304] = 2,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [321] = 2,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [338] = 2,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [355] = 2,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [372] = 2,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [389] = 2,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [406] = 2,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [423] = 2,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [440] = 2,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [457] = 2,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [474] = 2,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [491] = 2,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [508] = 2,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [525] = 2,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [542] = 8,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      sym_param_number,
    STATE(51), 1,
      sym_param_identifier,
    STATE(86), 1,
      sym_param_value,
    STATE(75), 3,
      sym_param_member_expression,
      sym_param_object,
      sym_param_string,
  [569] = 8,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      sym_param_number,
    STATE(51), 1,
      sym_param_identifier,
    STATE(116), 1,
      sym_param_value,
    STATE(75), 3,
      sym_param_member_expression,
      sym_param_object,
      sym_param_string,
  [596] = 8,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      sym_param_number,
    STATE(51), 1,
      sym_param_identifier,
    STATE(91), 1,
      sym_param_value,
    STATE(75), 3,
      sym_param_member_expression,
      sym_param_object,
      sym_param_string,
  [623] = 7,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      sym_param_property,
    STATE(85), 1,
      sym_param_identifier,
    STATE(111), 1,
      sym_param_string,
  [645] = 6,
    ACTIONS(145), 1,
      aux_sym_directive_name_token1,
    ACTIONS(147), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(52), 1,
      sym_identifier,
    STATE(95), 1,
      sym_member_expression,
    STATE(98), 1,
      sym_expression_content,
    STATE(99), 1,
      sym_function_call,
  [664] = 6,
    ACTIONS(149), 1,
      aux_sym_directive_name_token1,
    ACTIONS(151), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    STATE(60), 1,
      sym_identifier,
    STATE(103), 1,
      sym_function_call,
    STATE(104), 1,
      sym_member_expression,
    STATE(125), 1,
      sym_expression_content,
  [683] = 6,
    ACTIONS(147), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    ACTIONS(149), 1,
      aux_sym_directive_name_token1,
    STATE(60), 1,
      sym_identifier,
    STATE(103), 1,
      sym_function_call,
    STATE(104), 1,
      sym_member_expression,
    STATE(114), 1,
      sym_expression_content,
  [702] = 5,
    ACTIONS(153), 1,
      anon_sym_SQUOTE,
    ACTIONS(155), 1,
      sym_attribute_text,
    ACTIONS(157), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(159), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    STATE(38), 2,
      sym_output_expression,
      aux_sym_mixed_attribute_value_repeat1,
  [719] = 5,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(161), 1,
      sym_attribute_text,
    ACTIONS(163), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(165), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    STATE(37), 2,
      sym_output_expression,
      aux_sym_mixed_attribute_value_repeat1,
  [736] = 1,
    ACTIONS(167), 6,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_in,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [745] = 5,
    ACTIONS(163), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(165), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(169), 1,
      anon_sym_DQUOTE,
    ACTIONS(171), 1,
      sym_attribute_text,
    STATE(40), 2,
      sym_output_expression,
      aux_sym_mixed_attribute_value_repeat1,
  [762] = 5,
    ACTIONS(157), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(159), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(169), 1,
      anon_sym_SQUOTE,
    ACTIONS(173), 1,
      sym_attribute_text,
    STATE(41), 2,
      sym_output_expression,
      aux_sym_mixed_attribute_value_repeat1,
  [779] = 5,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    STATE(89), 1,
      sym_param_property,
    STATE(111), 2,
      sym_param_identifier,
      sym_param_string,
  [796] = 5,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      sym_attribute_text,
    ACTIONS(180), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(183), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    STATE(40), 2,
      sym_output_expression,
      aux_sym_mixed_attribute_value_repeat1,
  [813] = 5,
    ACTIONS(175), 1,
      anon_sym_SQUOTE,
    ACTIONS(186), 1,
      sym_attribute_text,
    ACTIONS(189), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(192), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    STATE(41), 2,
      sym_output_expression,
      aux_sym_mixed_attribute_value_repeat1,
  [830] = 6,
    ACTIONS(145), 1,
      aux_sym_directive_name_token1,
    ACTIONS(195), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(52), 1,
      sym_identifier,
    STATE(95), 1,
      sym_member_expression,
    STATE(99), 1,
      sym_function_call,
    STATE(118), 1,
      sym_expression_content,
  [849] = 6,
    ACTIONS(149), 1,
      aux_sym_directive_name_token1,
    ACTIONS(195), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    STATE(60), 1,
      sym_identifier,
    STATE(103), 1,
      sym_function_call,
    STATE(104), 1,
      sym_member_expression,
    STATE(119), 1,
      sym_expression_content,
  [868] = 6,
    ACTIONS(145), 1,
      aux_sym_directive_name_token1,
    ACTIONS(151), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(52), 1,
      sym_identifier,
    STATE(95), 1,
      sym_member_expression,
    STATE(99), 1,
      sym_function_call,
    STATE(124), 1,
      sym_expression_content,
  [887] = 4,
    ACTIONS(197), 1,
      anon_sym_GT,
    ACTIONS(199), 1,
      anon_sym_SLASH_GT,
    ACTIONS(201), 1,
      sym_attribute_name,
    STATE(50), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [901] = 3,
    ACTIONS(205), 1,
      sym_attribute_name,
    ACTIONS(203), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [913] = 4,
    ACTIONS(208), 1,
      anon_sym_DOT,
    ACTIONS(212), 1,
      anon_sym_in,
    STATE(48), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(210), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [927] = 3,
    ACTIONS(208), 1,
      anon_sym_DOT,
    STATE(49), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(214), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [939] = 3,
    ACTIONS(216), 1,
      anon_sym_DOT,
    STATE(49), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(219), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [951] = 4,
    ACTIONS(201), 1,
      sym_attribute_name,
    ACTIONS(221), 1,
      anon_sym_GT,
    ACTIONS(223), 1,
      anon_sym_SLASH_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [965] = 3,
    ACTIONS(208), 1,
      anon_sym_DOT,
    STATE(48), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(210), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [977] = 4,
    ACTIONS(225), 1,
      anon_sym_DOT,
    ACTIONS(227), 1,
      anon_sym_LPAREN,
    ACTIONS(229), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(66), 1,
      aux_sym_member_expression_repeat1,
  [990] = 4,
    ACTIONS(231), 1,
      sym_attribute_value,
    ACTIONS(233), 1,
      anon_sym_DQUOTE,
    ACTIONS(235), 1,
      anon_sym_SQUOTE,
    STATE(64), 1,
      sym_mixed_attribute_value,
  [1003] = 4,
    ACTIONS(237), 1,
      anon_sym_BANG,
    ACTIONS(239), 1,
      aux_sym_directive_name_token1,
    STATE(4), 1,
      sym_directive_name,
    STATE(7), 1,
      sym_directive_component,
  [1016] = 2,
    ACTIONS(243), 1,
      anon_sym_EQ,
    ACTIONS(241), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1025] = 1,
    ACTIONS(219), 4,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1032] = 1,
    ACTIONS(245), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1039] = 1,
    ACTIONS(97), 4,
      anon_sym_DQUOTE,
      sym_attribute_text,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [1046] = 1,
    ACTIONS(117), 4,
      anon_sym_DQUOTE,
      sym_attribute_text,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [1053] = 4,
    ACTIONS(229), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    ACTIONS(247), 1,
      anon_sym_DOT,
    ACTIONS(249), 1,
      anon_sym_LPAREN,
    STATE(76), 1,
      aux_sym_member_expression_repeat1,
  [1066] = 1,
    ACTIONS(97), 4,
      anon_sym_SQUOTE,
      sym_attribute_text,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [1073] = 1,
    ACTIONS(117), 4,
      anon_sym_SQUOTE,
      sym_attribute_text,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [1080] = 3,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_parameter_sequence_repeat1,
  [1090] = 1,
    ACTIONS(255), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1096] = 1,
    ACTIONS(257), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1102] = 3,
    ACTIONS(225), 1,
      anon_sym_DOT,
    ACTIONS(259), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(82), 1,
      aux_sym_member_expression_repeat1,
  [1112] = 1,
    ACTIONS(261), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1118] = 3,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_param_object_repeat1,
  [1128] = 3,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      aux_sym_param_object_repeat1,
  [1138] = 3,
    ACTIONS(239), 1,
      aux_sym_directive_name_token1,
    STATE(5), 1,
      sym_directive_name,
    STATE(9), 1,
      sym_directive_component,
  [1148] = 1,
    ACTIONS(269), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1154] = 1,
    ACTIONS(271), 3,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RBRACE_RBRACE,
  [1160] = 3,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_parameter_sequence_repeat1,
  [1170] = 1,
    ACTIONS(278), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1176] = 1,
    ACTIONS(210), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1182] = 3,
    ACTIONS(247), 1,
      anon_sym_DOT,
    ACTIONS(259), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    STATE(79), 1,
      aux_sym_member_expression_repeat1,
  [1192] = 1,
    ACTIONS(280), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1198] = 3,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      aux_sym_param_object_repeat1,
  [1208] = 3,
    ACTIONS(287), 1,
      anon_sym_DOT,
    ACTIONS(290), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    STATE(79), 1,
      aux_sym_member_expression_repeat1,
  [1218] = 1,
    ACTIONS(271), 3,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1224] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_parameter_sequence_repeat1,
  [1234] = 3,
    ACTIONS(290), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(294), 1,
      anon_sym_DOT,
    STATE(82), 1,
      aux_sym_member_expression_repeat1,
  [1244] = 2,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    STATE(56), 1,
      sym_param_identifier,
  [1251] = 2,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
    ACTIONS(299), 1,
      aux_sym_function_call_token1,
  [1258] = 2,
    ACTIONS(265), 1,
      anon_sym_RBRACE,
    ACTIONS(301), 1,
      anon_sym_COLON,
  [1265] = 1,
    ACTIONS(273), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1270] = 2,
    ACTIONS(303), 1,
      aux_sym_directive_name_token1,
    STATE(10), 1,
      sym_directive_method,
  [1277] = 2,
    ACTIONS(149), 1,
      aux_sym_directive_name_token1,
    STATE(90), 1,
      sym_identifier,
  [1284] = 1,
    ACTIONS(285), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1289] = 1,
    ACTIONS(290), 2,
      anon_sym_DOT,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1294] = 1,
    ACTIONS(305), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1299] = 2,
    ACTIONS(145), 1,
      aux_sym_directive_name_token1,
    STATE(93), 1,
      sym_identifier,
  [1306] = 1,
    ACTIONS(290), 2,
      anon_sym_DOT,
      anon_sym_RBRACE_RBRACE,
  [1311] = 2,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    ACTIONS(309), 1,
      aux_sym_function_call_token1,
  [1318] = 1,
    ACTIONS(229), 1,
      anon_sym_RBRACE_RBRACE,
  [1322] = 1,
    ACTIONS(311), 1,
      sym_tag_name,
  [1326] = 1,
    ACTIONS(313), 1,
      sym_tag_name,
  [1330] = 1,
    ACTIONS(315), 1,
      anon_sym_RBRACE_RBRACE,
  [1334] = 1,
    ACTIONS(229), 1,
      anon_sym_RBRACE_RBRACE,
  [1338] = 1,
    ACTIONS(317), 1,
      aux_sym_param_string_token2,
  [1342] = 1,
    ACTIONS(319), 1,
      anon_sym_SQUOTE,
  [1346] = 1,
    ACTIONS(321), 1,
      anon_sym_RPAREN,
  [1350] = 1,
    ACTIONS(229), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1354] = 1,
    ACTIONS(229), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1358] = 1,
    ACTIONS(323), 1,
      anon_sym_RPAREN,
  [1362] = 1,
    ACTIONS(325), 1,
      anon_sym_GT,
  [1366] = 1,
    ACTIONS(327), 1,
      aux_sym_param_string_token1,
  [1370] = 1,
    ACTIONS(319), 1,
      anon_sym_DQUOTE,
  [1374] = 1,
    ACTIONS(329), 1,
      anon_sym_html,
  [1378] = 1,
    ACTIONS(331), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1382] = 1,
    ACTIONS(301), 1,
      anon_sym_COLON,
  [1386] = 1,
    ACTIONS(333), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1390] = 1,
    ACTIONS(335), 1,
      ts_builtin_sym_end,
  [1394] = 1,
    ACTIONS(315), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1398] = 1,
    ACTIONS(337), 1,
      anon_sym_GT,
  [1402] = 1,
    ACTIONS(339), 1,
      anon_sym_RPAREN,
  [1406] = 1,
    ACTIONS(331), 1,
      anon_sym_RBRACE_RBRACE,
  [1410] = 1,
    ACTIONS(341), 1,
      anon_sym_RBRACE_RBRACE,
  [1414] = 1,
    ACTIONS(341), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1418] = 1,
    ACTIONS(343), 1,
      aux_sym_doctype_token1,
  [1422] = 1,
    ACTIONS(345), 1,
      anon_sym_RPAREN,
  [1426] = 1,
    ACTIONS(347), 1,
      anon_sym_RPAREN,
  [1430] = 1,
    ACTIONS(333), 1,
      anon_sym_RBRACE_RBRACE,
  [1434] = 1,
    ACTIONS(349), 1,
      anon_sym_RBRACE_RBRACE,
  [1438] = 1,
    ACTIONS(349), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 122,
  [SMALL_STATE(6)] = 148,
  [SMALL_STATE(7)] = 186,
  [SMALL_STATE(8)] = 209,
  [SMALL_STATE(9)] = 228,
  [SMALL_STATE(10)] = 251,
  [SMALL_STATE(11)] = 269,
  [SMALL_STATE(12)] = 287,
  [SMALL_STATE(13)] = 304,
  [SMALL_STATE(14)] = 321,
  [SMALL_STATE(15)] = 338,
  [SMALL_STATE(16)] = 355,
  [SMALL_STATE(17)] = 372,
  [SMALL_STATE(18)] = 389,
  [SMALL_STATE(19)] = 406,
  [SMALL_STATE(20)] = 423,
  [SMALL_STATE(21)] = 440,
  [SMALL_STATE(22)] = 457,
  [SMALL_STATE(23)] = 474,
  [SMALL_STATE(24)] = 491,
  [SMALL_STATE(25)] = 508,
  [SMALL_STATE(26)] = 525,
  [SMALL_STATE(27)] = 542,
  [SMALL_STATE(28)] = 569,
  [SMALL_STATE(29)] = 596,
  [SMALL_STATE(30)] = 623,
  [SMALL_STATE(31)] = 645,
  [SMALL_STATE(32)] = 664,
  [SMALL_STATE(33)] = 683,
  [SMALL_STATE(34)] = 702,
  [SMALL_STATE(35)] = 719,
  [SMALL_STATE(36)] = 736,
  [SMALL_STATE(37)] = 745,
  [SMALL_STATE(38)] = 762,
  [SMALL_STATE(39)] = 779,
  [SMALL_STATE(40)] = 796,
  [SMALL_STATE(41)] = 813,
  [SMALL_STATE(42)] = 830,
  [SMALL_STATE(43)] = 849,
  [SMALL_STATE(44)] = 868,
  [SMALL_STATE(45)] = 887,
  [SMALL_STATE(46)] = 901,
  [SMALL_STATE(47)] = 913,
  [SMALL_STATE(48)] = 927,
  [SMALL_STATE(49)] = 939,
  [SMALL_STATE(50)] = 951,
  [SMALL_STATE(51)] = 965,
  [SMALL_STATE(52)] = 977,
  [SMALL_STATE(53)] = 990,
  [SMALL_STATE(54)] = 1003,
  [SMALL_STATE(55)] = 1016,
  [SMALL_STATE(56)] = 1025,
  [SMALL_STATE(57)] = 1032,
  [SMALL_STATE(58)] = 1039,
  [SMALL_STATE(59)] = 1046,
  [SMALL_STATE(60)] = 1053,
  [SMALL_STATE(61)] = 1066,
  [SMALL_STATE(62)] = 1073,
  [SMALL_STATE(63)] = 1080,
  [SMALL_STATE(64)] = 1090,
  [SMALL_STATE(65)] = 1096,
  [SMALL_STATE(66)] = 1102,
  [SMALL_STATE(67)] = 1112,
  [SMALL_STATE(68)] = 1118,
  [SMALL_STATE(69)] = 1128,
  [SMALL_STATE(70)] = 1138,
  [SMALL_STATE(71)] = 1148,
  [SMALL_STATE(72)] = 1154,
  [SMALL_STATE(73)] = 1160,
  [SMALL_STATE(74)] = 1170,
  [SMALL_STATE(75)] = 1176,
  [SMALL_STATE(76)] = 1182,
  [SMALL_STATE(77)] = 1192,
  [SMALL_STATE(78)] = 1198,
  [SMALL_STATE(79)] = 1208,
  [SMALL_STATE(80)] = 1218,
  [SMALL_STATE(81)] = 1224,
  [SMALL_STATE(82)] = 1234,
  [SMALL_STATE(83)] = 1244,
  [SMALL_STATE(84)] = 1251,
  [SMALL_STATE(85)] = 1258,
  [SMALL_STATE(86)] = 1265,
  [SMALL_STATE(87)] = 1270,
  [SMALL_STATE(88)] = 1277,
  [SMALL_STATE(89)] = 1284,
  [SMALL_STATE(90)] = 1289,
  [SMALL_STATE(91)] = 1294,
  [SMALL_STATE(92)] = 1299,
  [SMALL_STATE(93)] = 1306,
  [SMALL_STATE(94)] = 1311,
  [SMALL_STATE(95)] = 1318,
  [SMALL_STATE(96)] = 1322,
  [SMALL_STATE(97)] = 1326,
  [SMALL_STATE(98)] = 1330,
  [SMALL_STATE(99)] = 1334,
  [SMALL_STATE(100)] = 1338,
  [SMALL_STATE(101)] = 1342,
  [SMALL_STATE(102)] = 1346,
  [SMALL_STATE(103)] = 1350,
  [SMALL_STATE(104)] = 1354,
  [SMALL_STATE(105)] = 1358,
  [SMALL_STATE(106)] = 1362,
  [SMALL_STATE(107)] = 1366,
  [SMALL_STATE(108)] = 1370,
  [SMALL_STATE(109)] = 1374,
  [SMALL_STATE(110)] = 1378,
  [SMALL_STATE(111)] = 1382,
  [SMALL_STATE(112)] = 1386,
  [SMALL_STATE(113)] = 1390,
  [SMALL_STATE(114)] = 1394,
  [SMALL_STATE(115)] = 1398,
  [SMALL_STATE(116)] = 1402,
  [SMALL_STATE(117)] = 1406,
  [SMALL_STATE(118)] = 1410,
  [SMALL_STATE(119)] = 1414,
  [SMALL_STATE(120)] = 1418,
  [SMALL_STATE(121)] = 1422,
  [SMALL_STATE(122)] = 1426,
  [SMALL_STATE(123)] = 1430,
  [SMALL_STATE(124)] = 1434,
  [SMALL_STATE(125)] = 1438,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(120),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_statement, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_statement, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_statement, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_statement, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_name, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_name, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_component, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_component, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_method, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_method, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_tag, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_tag, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_expression, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_expression, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_keyword, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_keyword, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_expression, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_expression, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_statement, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_statement, 4, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_params, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_params, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_params, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_params, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_identifier, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_mixed_attribute_value_repeat1, 2, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mixed_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [180] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mixed_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [183] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mixed_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [186] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mixed_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mixed_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [192] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mixed_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_value, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_member_expression, 2, 0, 0),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_member_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_member_expression_repeat1, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_content, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_string, 3, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_sequence, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_object, 3, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 2, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_object, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mixed_attribute_value, 2, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_sequence_repeat1, 2, 0, 0),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mixed_attribute_value, 3, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_object, 4, 0, 0),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_object_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_object_repeat1, 2, 0, 0),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_member_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_member_expression_repeat1, 2, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_parameter, 1, 0, 0),
  [294] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_member_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_property, 3, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [335] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_parameter, 3, 0, 0),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_edge(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "edge",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
