/* Automatically @generated by tree-sitter v0.25.5 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 110
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 75
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_LT_SLASH = 3,
  anon_sym_SLASH_GT = 4,
  anon_sym_LT_BANGDOCTYPE = 5,
  aux_sym_doctype_token1 = 6,
  anon_sym_html = 7,
  sym_tag_name = 8,
  anon_sym_EQ = 9,
  sym_attribute_name = 10,
  sym_attribute_value = 11,
  anon_sym_DQUOTE = 12,
  aux_sym_quoted_attribute_value_token1 = 13,
  anon_sym_SQUOTE = 14,
  aux_sym_quoted_attribute_value_token2 = 15,
  anon_sym_AT = 16,
  anon_sym_BANG = 17,
  anon_sym_DOT = 18,
  anon_sym_ATend = 19,
  anon_sym_ATelse = 20,
  anon_sym_ATelseif = 21,
  aux_sym_directive_name_token1 = 22,
  anon_sym_LPAREN = 23,
  anon_sym_RPAREN = 24,
  anon_sym_COMMA = 25,
  anon_sym_in = 26,
  anon_sym_LBRACE = 27,
  anon_sym_RBRACE = 28,
  anon_sym_COLON = 29,
  sym_param_number = 30,
  anon_sym_LBRACE_LBRACE = 31,
  anon_sym_RBRACE_RBRACE = 32,
  anon_sym_LBRACE_LBRACE_LBRACE = 33,
  anon_sym_RBRACE_RBRACE_RBRACE = 34,
  aux_sym_function_call_token1 = 35,
  sym_comment = 36,
  sym_text_content = 37,
  sym_source_file = 38,
  sym__content = 39,
  sym_html_tag = 40,
  sym_start_tag = 41,
  sym_end_tag = 42,
  sym_self_closing_tag = 43,
  sym_doctype = 44,
  sym_attribute = 45,
  sym_quoted_attribute_value = 46,
  sym_directive = 47,
  sym_directive_statement = 48,
  sym_directive_component = 49,
  sym_directive_keyword = 50,
  sym_directive_name = 51,
  sym_directive_method = 52,
  sym_directive_params = 53,
  sym_parameter_list = 54,
  sym_single_parameter = 55,
  sym_parameter_sequence = 56,
  sym_each_parameter = 57,
  sym_param_value = 58,
  sym_param_member_expression = 59,
  sym_param_object = 60,
  sym_param_property = 61,
  sym_param_identifier = 62,
  sym_param_string = 63,
  sym_output_expression = 64,
  sym_expression_content = 65,
  sym_function_call = 66,
  sym_member_expression = 67,
  sym_identifier = 68,
  aux_sym_source_file_repeat1 = 69,
  aux_sym_start_tag_repeat1 = 70,
  aux_sym_parameter_sequence_repeat1 = 71,
  aux_sym_param_member_expression_repeat1 = 72,
  aux_sym_param_object_repeat1 = 73,
  aux_sym_member_expression_repeat1 = 74,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_BANGDOCTYPE] = "<!DOCTYPE",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_html] = "html",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token1] = "quoted_attribute_value_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token2] = "quoted_attribute_value_token2",
  [anon_sym_AT] = "@",
  [anon_sym_BANG] = "!",
  [anon_sym_DOT] = ".",
  [anon_sym_ATend] = "@end",
  [anon_sym_ATelse] = "@else",
  [anon_sym_ATelseif] = "@elseif",
  [aux_sym_directive_name_token1] = "directive_name_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_in] = "in",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_param_number] = "param_number",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_LBRACE_LBRACE] = "{{{",
  [anon_sym_RBRACE_RBRACE_RBRACE] = "}}}",
  [aux_sym_function_call_token1] = "function_call_token1",
  [sym_comment] = "comment",
  [sym_text_content] = "text_content",
  [sym_source_file] = "source_file",
  [sym__content] = "_content",
  [sym_html_tag] = "html_tag",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_doctype] = "doctype",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_directive] = "directive",
  [sym_directive_statement] = "directive_statement",
  [sym_directive_component] = "directive_component",
  [sym_directive_keyword] = "directive_keyword",
  [sym_directive_name] = "directive_name",
  [sym_directive_method] = "directive_method",
  [sym_directive_params] = "directive_params",
  [sym_parameter_list] = "parameter_list",
  [sym_single_parameter] = "single_parameter",
  [sym_parameter_sequence] = "parameter_sequence",
  [sym_each_parameter] = "each_parameter",
  [sym_param_value] = "param_value",
  [sym_param_member_expression] = "param_member_expression",
  [sym_param_object] = "param_object",
  [sym_param_property] = "param_property",
  [sym_param_identifier] = "param_identifier",
  [sym_param_string] = "param_string",
  [sym_output_expression] = "output_expression",
  [sym_expression_content] = "expression_content",
  [sym_function_call] = "function_call",
  [sym_member_expression] = "member_expression",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_parameter_sequence_repeat1] = "parameter_sequence_repeat1",
  [aux_sym_param_member_expression_repeat1] = "param_member_expression_repeat1",
  [aux_sym_param_object_repeat1] = "param_object_repeat1",
  [aux_sym_member_expression_repeat1] = "member_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_BANGDOCTYPE] = anon_sym_LT_BANGDOCTYPE,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_html] = anon_sym_html,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token1] = aux_sym_quoted_attribute_value_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token2] = aux_sym_quoted_attribute_value_token2,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_ATend] = anon_sym_ATend,
  [anon_sym_ATelse] = anon_sym_ATelse,
  [anon_sym_ATelseif] = anon_sym_ATelseif,
  [aux_sym_directive_name_token1] = aux_sym_directive_name_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_param_number] = sym_param_number,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE_RBRACE,
  [aux_sym_function_call_token1] = aux_sym_function_call_token1,
  [sym_comment] = sym_comment,
  [sym_text_content] = sym_text_content,
  [sym_source_file] = sym_source_file,
  [sym__content] = sym__content,
  [sym_html_tag] = sym_html_tag,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_doctype] = sym_doctype,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_directive] = sym_directive,
  [sym_directive_statement] = sym_directive_statement,
  [sym_directive_component] = sym_directive_component,
  [sym_directive_keyword] = sym_directive_keyword,
  [sym_directive_name] = sym_directive_name,
  [sym_directive_method] = sym_directive_method,
  [sym_directive_params] = sym_directive_params,
  [sym_parameter_list] = sym_parameter_list,
  [sym_single_parameter] = sym_single_parameter,
  [sym_parameter_sequence] = sym_parameter_sequence,
  [sym_each_parameter] = sym_each_parameter,
  [sym_param_value] = sym_param_value,
  [sym_param_member_expression] = sym_param_member_expression,
  [sym_param_object] = sym_param_object,
  [sym_param_property] = sym_param_property,
  [sym_param_identifier] = sym_param_identifier,
  [sym_param_string] = sym_param_string,
  [sym_output_expression] = sym_output_expression,
  [sym_expression_content] = sym_expression_content,
  [sym_function_call] = sym_function_call,
  [sym_member_expression] = sym_member_expression,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_parameter_sequence_repeat1] = aux_sym_parameter_sequence_repeat1,
  [aux_sym_param_member_expression_repeat1] = aux_sym_param_member_expression_repeat1,
  [aux_sym_param_object_repeat1] = aux_sym_param_object_repeat1,
  [aux_sym_member_expression_repeat1] = aux_sym_member_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_BANGDOCTYPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_html] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATelse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATelseif] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_param_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_function_call_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__content] = {
    .visible = false,
    .named = true,
  },
  [sym_html_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_component] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_method] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_params] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_single_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_each_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_param_value] = {
    .visible = true,
    .named = true,
  },
  [sym_param_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_param_object] = {
    .visible = true,
    .named = true,
  },
  [sym_param_property] = {
    .visible = true,
    .named = true,
  },
  [sym_param_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_param_string] = {
    .visible = true,
    .named = true,
  },
  [sym_output_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_content] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_member_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_member_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 42,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 55,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 52,
  [67] = 67,
  [68] = 53,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 69,
  [81] = 75,
  [82] = 71,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 94,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 83,
  [106] = 106,
  [107] = 97,
  [108] = 108,
  [109] = 91,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '!', 57,
        '"', 50,
        '\'', 53,
        '(', 63,
        ')', 64,
        ',', 65,
        '.', 58,
        '/', 9,
        ':', 70,
        '<', 39,
        '=', 47,
        '>', 40,
        '@', 56,
        'h', 25,
        'i', 23,
        '{', 68,
        '}', 69,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(57);
      if (lookahead == '"') ADVANCE(50);
      if (lookahead == '\'') ADVANCE(53);
      if (lookahead == ')') ADVANCE(64);
      if (lookahead == '{') ADVANCE(67);
      if (lookahead == '}') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(50);
      if (lookahead == '\'') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '`') ADVANCE(49);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(63);
      if (lookahead == '.') ADVANCE(58);
      if (lookahead == '}') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(63);
      if (lookahead == '.') ADVANCE(58);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(27);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '=') ADVANCE(47);
      if (lookahead == '>') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == 'C') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'D') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(43);
      END_STATE();
    case 13:
      if (lookahead == 'O') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'P') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'T') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 'Y') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(59);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(61);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == '{') ADVANCE(73);
      END_STATE();
    case 27:
      if (lookahead == '}') ADVANCE(28);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 28:
      if (lookahead == '}') ADVANCE(79);
      END_STATE();
    case 29:
      if (lookahead == '}') ADVANCE(74);
      END_STATE();
    case 30:
      if (lookahead == '}') ADVANCE(76);
      END_STATE();
    case 31:
      if (lookahead == '}') ADVANCE(30);
      END_STATE();
    case 32:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 33:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 35:
      if (eof) ADVANCE(38);
      if (lookahead == '(') ADVANCE(63);
      if (lookahead == '.') ADVANCE(58);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '@') ADVANCE(56);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 36:
      if (eof) ADVANCE(38);
      if (lookahead == '(') ADVANCE(63);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '@') ADVANCE(56);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '@') ADVANCE(56);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == '/') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LT_BANGDOCTYPE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_html);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '`') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_ATelse);
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_ATelseif);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_directive_name_token1);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(73);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_param_number);
      if (lookahead == '.') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_param_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '{') ADVANCE(75);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_LBRACE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE_RBRACE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '(') ADVANCE(63);
      if (lookahead == '.') ADVANCE(58);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '@') ADVANCE(56);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '(') ADVANCE(63);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '@') ADVANCE(56);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '@') ADVANCE(56);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '@' &&
          lookahead != '{') ADVANCE(83);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 37},
  [2] = {.lex_state = 37},
  [3] = {.lex_state = 37},
  [4] = {.lex_state = 35},
  [5] = {.lex_state = 35},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 36},
  [8] = {.lex_state = 35},
  [9] = {.lex_state = 36},
  [10] = {.lex_state = 36},
  [11] = {.lex_state = 36},
  [12] = {.lex_state = 37},
  [13] = {.lex_state = 37},
  [14] = {.lex_state = 37},
  [15] = {.lex_state = 37},
  [16] = {.lex_state = 37},
  [17] = {.lex_state = 37},
  [18] = {.lex_state = 37},
  [19] = {.lex_state = 37},
  [20] = {.lex_state = 37},
  [21] = {.lex_state = 37},
  [22] = {.lex_state = 37},
  [23] = {.lex_state = 37},
  [24] = {.lex_state = 37},
  [25] = {.lex_state = 37},
  [26] = {.lex_state = 37},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 8},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 77},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 51},
  [78] = {.lex_state = 54},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 4},
  [82] = {.lex_state = 77},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 32},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 33},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 4},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 33},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 4},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 51},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 4},
  [106] = {.lex_state = 54},
  [107] = {.lex_state = 4},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_BANGDOCTYPE] = ACTIONS(1),
    [anon_sym_html] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [anon_sym_ATelse] = ACTIONS(1),
    [anon_sym_ATelseif] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_param_number] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(108),
    [sym__content] = STATE(3),
    [sym_html_tag] = STATE(3),
    [sym_start_tag] = STATE(13),
    [sym_end_tag] = STATE(13),
    [sym_self_closing_tag] = STATE(13),
    [sym_doctype] = STATE(3),
    [sym_directive] = STATE(3),
    [sym_directive_statement] = STATE(12),
    [sym_directive_keyword] = STATE(12),
    [sym_output_expression] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [anon_sym_LT_SLASH] = ACTIONS(7),
    [anon_sym_LT_BANGDOCTYPE] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_ATend] = ACTIONS(13),
    [anon_sym_ATelse] = ACTIONS(13),
    [anon_sym_ATelseif] = ACTIONS(13),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(17),
    [sym_comment] = ACTIONS(19),
    [sym_text_content] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(26), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      anon_sym_LT_BANGDOCTYPE,
    ACTIONS(32), 1,
      anon_sym_AT,
    ACTIONS(38), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(41), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(44), 2,
      sym_comment,
      sym_text_content,
    STATE(12), 2,
      sym_directive_statement,
      sym_directive_keyword,
    ACTIONS(35), 3,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
    STATE(13), 3,
      sym_start_tag,
      sym_end_tag,
      sym_self_closing_tag,
    STATE(2), 6,
      sym__content,
      sym_html_tag,
      sym_doctype,
      sym_directive,
      sym_output_expression,
      aux_sym_source_file_repeat1,
  [48] = 12,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LT_SLASH,
    ACTIONS(9), 1,
      anon_sym_LT_BANGDOCTYPE,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 2,
      sym_comment,
      sym_text_content,
    STATE(12), 2,
      sym_directive_statement,
      sym_directive_keyword,
    ACTIONS(13), 3,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
    STATE(13), 3,
      sym_start_tag,
      sym_end_tag,
      sym_self_closing_tag,
    STATE(2), 6,
      sym__content,
      sym_html_tag,
      sym_doctype,
      sym_directive,
      sym_output_expression,
      aux_sym_source_file_repeat1,
  [96] = 5,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_directive_params,
    ACTIONS(53), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [122] = 5,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_directive_params,
    ACTIONS(61), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [148] = 11,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      sym_param_number,
    STATE(36), 1,
      sym_param_identifier,
    STATE(67), 1,
      sym_param_value,
    STATE(96), 1,
      sym_parameter_list,
    STATE(62), 3,
      sym_param_member_expression,
      sym_param_object,
      sym_param_string,
    STATE(98), 3,
      sym_single_parameter,
      sym_parameter_sequence,
      sym_each_parameter,
  [186] = 4,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_directive_params,
    ACTIONS(53), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [209] = 2,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 13,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LPAREN,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [228] = 4,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_directive_params,
    ACTIONS(61), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [251] = 2,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 12,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LPAREN,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [269] = 2,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 12,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LPAREN,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [287] = 2,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [304] = 2,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [321] = 2,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [338] = 2,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [355] = 2,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [372] = 2,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [389] = 2,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [406] = 2,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [423] = 2,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [440] = 2,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [457] = 2,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [474] = 2,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [491] = 2,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [508] = 2,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [525] = 2,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 11,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANGDOCTYPE,
      anon_sym_AT,
      anon_sym_ATend,
      anon_sym_ATelse,
      anon_sym_ATelseif,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      sym_comment,
      sym_text_content,
  [542] = 8,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      sym_param_number,
    STATE(40), 1,
      sym_param_identifier,
    STATE(74), 1,
      sym_param_value,
    STATE(62), 3,
      sym_param_member_expression,
      sym_param_object,
      sym_param_string,
  [569] = 8,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      sym_param_number,
    STATE(40), 1,
      sym_param_identifier,
    STATE(92), 1,
      sym_param_value,
    STATE(62), 3,
      sym_param_member_expression,
      sym_param_object,
      sym_param_string,
  [596] = 8,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      sym_param_number,
    STATE(40), 1,
      sym_param_identifier,
    STATE(79), 1,
      sym_param_value,
    STATE(62), 3,
      sym_param_member_expression,
      sym_param_object,
      sym_param_string,
  [623] = 7,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      sym_param_property,
    STATE(70), 1,
      sym_param_identifier,
    STATE(89), 1,
      sym_param_string,
  [645] = 5,
    ACTIONS(145), 1,
      aux_sym_directive_name_token1,
    ACTIONS(147), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(46), 1,
      sym_identifier,
    STATE(93), 1,
      sym_expression_content,
    STATE(94), 2,
      sym_function_call,
      sym_member_expression,
  [662] = 1,
    ACTIONS(149), 6,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_in,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [671] = 5,
    ACTIONS(147), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    ACTIONS(151), 1,
      aux_sym_directive_name_token1,
    STATE(42), 1,
      sym_identifier,
    STATE(88), 1,
      sym_expression_content,
    STATE(100), 2,
      sym_function_call,
      sym_member_expression,
  [688] = 5,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    STATE(76), 1,
      sym_param_property,
    STATE(89), 2,
      sym_param_identifier,
      sym_param_string,
  [705] = 3,
    ACTIONS(155), 1,
      sym_attribute_name,
    ACTIONS(153), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(35), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [717] = 4,
    ACTIONS(158), 1,
      anon_sym_DOT,
    ACTIONS(162), 1,
      anon_sym_in,
    STATE(38), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(160), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [731] = 4,
    ACTIONS(164), 1,
      anon_sym_GT,
    ACTIONS(166), 1,
      anon_sym_SLASH_GT,
    ACTIONS(168), 1,
      sym_attribute_name,
    STATE(39), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [745] = 3,
    ACTIONS(158), 1,
      anon_sym_DOT,
    STATE(41), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(170), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [757] = 4,
    ACTIONS(168), 1,
      sym_attribute_name,
    ACTIONS(172), 1,
      anon_sym_GT,
    ACTIONS(174), 1,
      anon_sym_SLASH_GT,
    STATE(35), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [771] = 3,
    ACTIONS(158), 1,
      anon_sym_DOT,
    STATE(38), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(160), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [783] = 3,
    ACTIONS(176), 1,
      anon_sym_DOT,
    STATE(41), 1,
      aux_sym_param_member_expression_repeat1,
    ACTIONS(179), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [795] = 4,
    ACTIONS(181), 1,
      anon_sym_DOT,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(185), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    STATE(68), 1,
      aux_sym_member_expression_repeat1,
  [808] = 4,
    ACTIONS(187), 1,
      anon_sym_BANG,
    ACTIONS(189), 1,
      aux_sym_directive_name_token1,
    STATE(4), 1,
      sym_directive_name,
    STATE(7), 1,
      sym_directive_component,
  [821] = 4,
    ACTIONS(191), 1,
      sym_attribute_value,
    ACTIONS(193), 1,
      anon_sym_DQUOTE,
    ACTIONS(195), 1,
      anon_sym_SQUOTE,
    STATE(56), 1,
      sym_quoted_attribute_value,
  [834] = 2,
    ACTIONS(199), 1,
      anon_sym_EQ,
    ACTIONS(197), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [843] = 4,
    ACTIONS(185), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(201), 1,
      anon_sym_DOT,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(53), 1,
      aux_sym_member_expression_repeat1,
  [856] = 1,
    ACTIONS(205), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [863] = 1,
    ACTIONS(179), 4,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [870] = 3,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      aux_sym_param_object_repeat1,
  [880] = 3,
    ACTIONS(189), 1,
      aux_sym_directive_name_token1,
    STATE(5), 1,
      sym_directive_name,
    STATE(9), 1,
      sym_directive_component,
  [890] = 3,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    STATE(60), 1,
      aux_sym_parameter_sequence_repeat1,
  [900] = 1,
    ACTIONS(215), 3,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RBRACE_RBRACE,
  [906] = 3,
    ACTIONS(201), 1,
      anon_sym_DOT,
    ACTIONS(217), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(55), 1,
      aux_sym_member_expression_repeat1,
  [916] = 1,
    ACTIONS(219), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [922] = 3,
    ACTIONS(221), 1,
      anon_sym_DOT,
    ACTIONS(224), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(55), 1,
      aux_sym_member_expression_repeat1,
  [932] = 1,
    ACTIONS(226), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [938] = 1,
    ACTIONS(228), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [944] = 3,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_param_object_repeat1,
  [954] = 1,
    ACTIONS(232), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [960] = 3,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    STATE(60), 1,
      aux_sym_parameter_sequence_repeat1,
  [970] = 3,
    ACTIONS(224), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    ACTIONS(239), 1,
      anon_sym_DOT,
    STATE(61), 1,
      aux_sym_member_expression_repeat1,
  [980] = 1,
    ACTIONS(160), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [986] = 1,
    ACTIONS(242), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [992] = 1,
    ACTIONS(244), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [998] = 3,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_param_object_repeat1,
  [1008] = 1,
    ACTIONS(215), 3,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1014] = 3,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_parameter_sequence_repeat1,
  [1024] = 3,
    ACTIONS(181), 1,
      anon_sym_DOT,
    ACTIONS(217), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    STATE(61), 1,
      aux_sym_member_expression_repeat1,
  [1034] = 2,
    ACTIONS(145), 1,
      aux_sym_directive_name_token1,
    STATE(75), 1,
      sym_identifier,
  [1041] = 2,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    ACTIONS(253), 1,
      anon_sym_COLON,
  [1048] = 2,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
    ACTIONS(257), 1,
      aux_sym_function_call_token1,
  [1055] = 2,
    ACTIONS(67), 1,
      aux_sym_directive_name_token1,
    STATE(48), 1,
      sym_param_identifier,
  [1062] = 2,
    ACTIONS(259), 1,
      aux_sym_directive_name_token1,
    STATE(10), 1,
      sym_directive_method,
  [1069] = 1,
    ACTIONS(234), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1074] = 1,
    ACTIONS(224), 2,
      anon_sym_DOT,
      anon_sym_RBRACE_RBRACE,
  [1079] = 1,
    ACTIONS(249), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1084] = 2,
    ACTIONS(261), 1,
      anon_sym_DQUOTE,
    ACTIONS(263), 1,
      aux_sym_quoted_attribute_value_token1,
  [1091] = 2,
    ACTIONS(261), 1,
      anon_sym_SQUOTE,
    ACTIONS(265), 1,
      aux_sym_quoted_attribute_value_token2,
  [1098] = 1,
    ACTIONS(267), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1103] = 2,
    ACTIONS(151), 1,
      aux_sym_directive_name_token1,
    STATE(81), 1,
      sym_identifier,
  [1110] = 1,
    ACTIONS(224), 2,
      anon_sym_DOT,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1115] = 2,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
    ACTIONS(271), 1,
      aux_sym_function_call_token1,
  [1122] = 1,
    ACTIONS(273), 1,
      anon_sym_RBRACE_RBRACE,
  [1126] = 1,
    ACTIONS(275), 1,
      aux_sym_doctype_token1,
  [1130] = 1,
    ACTIONS(277), 1,
      anon_sym_GT,
  [1134] = 1,
    ACTIONS(279), 1,
      sym_tag_name,
  [1138] = 1,
    ACTIONS(281), 1,
      anon_sym_GT,
  [1142] = 1,
    ACTIONS(283), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1146] = 1,
    ACTIONS(253), 1,
      anon_sym_COLON,
  [1150] = 1,
    ACTIONS(285), 1,
      anon_sym_html,
  [1154] = 1,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
  [1158] = 1,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
  [1162] = 1,
    ACTIONS(283), 1,
      anon_sym_RBRACE_RBRACE,
  [1166] = 1,
    ACTIONS(185), 1,
      anon_sym_RBRACE_RBRACE,
  [1170] = 1,
    ACTIONS(291), 1,
      sym_tag_name,
  [1174] = 1,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
  [1178] = 1,
    ACTIONS(295), 1,
      anon_sym_RBRACE_RBRACE,
  [1182] = 1,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
  [1186] = 1,
    ACTIONS(299), 1,
      anon_sym_DQUOTE,
  [1190] = 1,
    ACTIONS(185), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1194] = 1,
    ACTIONS(299), 1,
      anon_sym_SQUOTE,
  [1198] = 1,
    ACTIONS(301), 1,
      anon_sym_DQUOTE,
  [1202] = 1,
    ACTIONS(303), 1,
      aux_sym_quoted_attribute_value_token1,
  [1206] = 1,
    ACTIONS(301), 1,
      anon_sym_SQUOTE,
  [1210] = 1,
    ACTIONS(273), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1214] = 1,
    ACTIONS(305), 1,
      aux_sym_quoted_attribute_value_token2,
  [1218] = 1,
    ACTIONS(295), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [1222] = 1,
    ACTIONS(307), 1,
      ts_builtin_sym_end,
  [1226] = 1,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 122,
  [SMALL_STATE(6)] = 148,
  [SMALL_STATE(7)] = 186,
  [SMALL_STATE(8)] = 209,
  [SMALL_STATE(9)] = 228,
  [SMALL_STATE(10)] = 251,
  [SMALL_STATE(11)] = 269,
  [SMALL_STATE(12)] = 287,
  [SMALL_STATE(13)] = 304,
  [SMALL_STATE(14)] = 321,
  [SMALL_STATE(15)] = 338,
  [SMALL_STATE(16)] = 355,
  [SMALL_STATE(17)] = 372,
  [SMALL_STATE(18)] = 389,
  [SMALL_STATE(19)] = 406,
  [SMALL_STATE(20)] = 423,
  [SMALL_STATE(21)] = 440,
  [SMALL_STATE(22)] = 457,
  [SMALL_STATE(23)] = 474,
  [SMALL_STATE(24)] = 491,
  [SMALL_STATE(25)] = 508,
  [SMALL_STATE(26)] = 525,
  [SMALL_STATE(27)] = 542,
  [SMALL_STATE(28)] = 569,
  [SMALL_STATE(29)] = 596,
  [SMALL_STATE(30)] = 623,
  [SMALL_STATE(31)] = 645,
  [SMALL_STATE(32)] = 662,
  [SMALL_STATE(33)] = 671,
  [SMALL_STATE(34)] = 688,
  [SMALL_STATE(35)] = 705,
  [SMALL_STATE(36)] = 717,
  [SMALL_STATE(37)] = 731,
  [SMALL_STATE(38)] = 745,
  [SMALL_STATE(39)] = 757,
  [SMALL_STATE(40)] = 771,
  [SMALL_STATE(41)] = 783,
  [SMALL_STATE(42)] = 795,
  [SMALL_STATE(43)] = 808,
  [SMALL_STATE(44)] = 821,
  [SMALL_STATE(45)] = 834,
  [SMALL_STATE(46)] = 843,
  [SMALL_STATE(47)] = 856,
  [SMALL_STATE(48)] = 863,
  [SMALL_STATE(49)] = 870,
  [SMALL_STATE(50)] = 880,
  [SMALL_STATE(51)] = 890,
  [SMALL_STATE(52)] = 900,
  [SMALL_STATE(53)] = 906,
  [SMALL_STATE(54)] = 916,
  [SMALL_STATE(55)] = 922,
  [SMALL_STATE(56)] = 932,
  [SMALL_STATE(57)] = 938,
  [SMALL_STATE(58)] = 944,
  [SMALL_STATE(59)] = 954,
  [SMALL_STATE(60)] = 960,
  [SMALL_STATE(61)] = 970,
  [SMALL_STATE(62)] = 980,
  [SMALL_STATE(63)] = 986,
  [SMALL_STATE(64)] = 992,
  [SMALL_STATE(65)] = 998,
  [SMALL_STATE(66)] = 1008,
  [SMALL_STATE(67)] = 1014,
  [SMALL_STATE(68)] = 1024,
  [SMALL_STATE(69)] = 1034,
  [SMALL_STATE(70)] = 1041,
  [SMALL_STATE(71)] = 1048,
  [SMALL_STATE(72)] = 1055,
  [SMALL_STATE(73)] = 1062,
  [SMALL_STATE(74)] = 1069,
  [SMALL_STATE(75)] = 1074,
  [SMALL_STATE(76)] = 1079,
  [SMALL_STATE(77)] = 1084,
  [SMALL_STATE(78)] = 1091,
  [SMALL_STATE(79)] = 1098,
  [SMALL_STATE(80)] = 1103,
  [SMALL_STATE(81)] = 1110,
  [SMALL_STATE(82)] = 1115,
  [SMALL_STATE(83)] = 1122,
  [SMALL_STATE(84)] = 1126,
  [SMALL_STATE(85)] = 1130,
  [SMALL_STATE(86)] = 1134,
  [SMALL_STATE(87)] = 1138,
  [SMALL_STATE(88)] = 1142,
  [SMALL_STATE(89)] = 1146,
  [SMALL_STATE(90)] = 1150,
  [SMALL_STATE(91)] = 1154,
  [SMALL_STATE(92)] = 1158,
  [SMALL_STATE(93)] = 1162,
  [SMALL_STATE(94)] = 1166,
  [SMALL_STATE(95)] = 1170,
  [SMALL_STATE(96)] = 1174,
  [SMALL_STATE(97)] = 1178,
  [SMALL_STATE(98)] = 1182,
  [SMALL_STATE(99)] = 1186,
  [SMALL_STATE(100)] = 1190,
  [SMALL_STATE(101)] = 1194,
  [SMALL_STATE(102)] = 1198,
  [SMALL_STATE(103)] = 1202,
  [SMALL_STATE(104)] = 1206,
  [SMALL_STATE(105)] = 1210,
  [SMALL_STATE(106)] = 1214,
  [SMALL_STATE(107)] = 1218,
  [SMALL_STATE(108)] = 1222,
  [SMALL_STATE(109)] = 1226,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_statement, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_statement, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_statement, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_statement, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_name, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_name, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_component, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_component, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_method, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_method, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_tag, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_tag, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_expression, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_expression, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_keyword, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_keyword, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_expression, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_expression, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_statement, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_statement, 4, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_params, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_params, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_params, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_params, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_identifier, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_value, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_member_expression, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_member_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_member_expression_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_content, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_string, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_sequence, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_member_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_member_expression_repeat1, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_object, 3, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_object, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_sequence_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_member_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_object, 4, 0, 0),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_object_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_object_repeat1, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_parameter, 1, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_property, 3, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_parameter, 3, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [307] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_edge(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "edge",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
